name: 📃 Blank Issue
description: Create a blank issue. 

body:
    - type: markdown
      attributes:
          value: |
           Thanks for taking the time to report a issue! Please fill out the form below as thoroughly as possible.

    - type: textarea
      id: content
      attributes:
          label: Content
      validations:
          required: true

    - type: checkboxes
      id: agreement-check
      attributes:
          label: Confirmation
          options:
              - label: I have searched existing issues and confirmed this is not a duplicate.
                required: true
