name: Build and Dev Server Check

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run build and time it
        run: |
          START=$(date +%s.%N)
          npm run build
          END=$(date +%s.%N)
          DIFF=$(echo "$END - $START" | bc)
          echo "✓ Built in ${DIFF}s"

      - name: Start dev server briefly and check output
        run: |
          timeout 10s npm run dev > output.log 2>&1 || true
          cat output.log
          grep -E "Local:   http://localhost:5173/" output.log
