name: Build and Dev Server Check

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run build and time it
        run: |
          START=$(date +%s.%N)
          npm run build
          END=$(date +%s.%N)
          DIFF=$(echo "$END - $START" | bc)
          echo "✓ Built in ${DIFF}s"

